name: Run Docker Image, Show Databases, and Tables

on:
  push:
    paths: .github/workflows/my-flow2.yml

jobs:
  build:
    runs-on: ubuntu-latest
    container: hamzasamara/mysql-01

    steps:
      - uses: actions/checkout@v3

      - name: Start MySQL
        run: mysqld &  # Start MySQL in the background
      
      - name: Wait for MySQL to start
        run: sleep 20  # Adjust the sleep time as necessary
      
      - name: Show databases
        run: mysql -uroot -prootpassword -e "SHOW DATABASES;"  # Show databases
      
      - name: Show School Database Tables
        run: mysql -uroot -prootpassword -e "USE school; SHOW TABLES;" # Show tables
      
      - name: Display Table content
        run: mysql -uroot -prootpassword -e "USE school; SHOW TABLES; SELECT * FROM students;"  # Display table content
